/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_zhuran_jni_NativePrinter */

#ifndef _Included_cc_zhuran_jni_NativePrinter
#define _Included_cc_zhuran_jni_NativePrinter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_zhuran_jni_NativePrinter
 * Method:    print
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cc_zhuran_jni_NativePrinter_print
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
